/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Ioana
 */
public class BookStoreOperation extends javax.swing.JFrame {

    /**
     * Creates new form BookStoreOperation
     */
    public BookStoreOperation() {
        initComponents();
        displayPanel();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setColumns(15);

        jButton1.setText("jButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");

        jTextField2.setColumns(15);

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setText("jButton2");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextField7.setColumns(15);

        jLabel6.setText("jLabel6");

        jTextField4.setColumns(15);

        jTextField6.setColumns(15);

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel7.setText("jLabel7");

        jTextField3.setColumns(15);

        jLabel8.setText("jLabel8");

        jTextField5.setColumns(15);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ShareData d;
    public void displayPanel()
    {
        d=new ShareData();
        String s=d.getType();
        if(s.equals("employee"))
        {
            jButton1.setVisible(true);
            jPanel1.setVisible(true);
            jTextField1.setVisible(true);
            jScrollPane1.setVisible(true);
            jTextArea1.setVisible(true);
            jPanel2.setVisible(false);
            this.setSize(700,500 );
            jLabel1.setVisible(false);
            jPanel1.setBounds(javax.swing.JFrame.WIDTH, javax.swing.JFrame.HEIGHT, javax.swing.JFrame.WIDTH, javax.swing.JFrame.WIDTH);
            functie();
        }
        else
        {
            jButton1.setVisible(false);
            jPanel1.setVisible(false);
            jTextField1.setVisible(false);
            jScrollPane1.setVisible(false);
            jTextArea1.setVisible(false);
            jPanel2.setVisible(true);
            jScrollPane1.setVisible(false);
            jTextArea1.setVisible(false);
            this.setSize(700,500 );
            jPanel2.setBounds(javax.swing.JFrame.WIDTH, javax.swing.JFrame.HEIGHT, javax.swing.JFrame.WIDTH, javax.swing.JFrame.WIDTH);
            functieAdmin();
            
        }
    }
    public void functie()
    {
        String[] options = new String[] {"Genre","Author","Title","Sell Book"};
        int response = JOptionPane.showOptionDialog(null, "Search books by", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
        if(response==0)    
        {
            jLabel2.setText("Genre");
            jButton1.setText("Genre");
            jLabel3.setVisible(false);
            jTextField2.setVisible(false);
            jTextField1.setText("");
            jTextArea1.setText("");
             
        }
        if(response==1)    
        {
            jLabel2.setText("Author");
            jButton1.setText("Author");
            jLabel3.setVisible(false);
            jTextField2.setVisible(false);
            jTextField1.setText("");
            jTextArea1.setText("");
        }
        if(response==2)    
        {
            jLabel2.setText("Title");
            jButton1.setText("Title");
            jLabel3.setVisible(false);
            jTextField2.setVisible(false);
            jTextField1.setText("");
            jTextArea1.setText("");

        }
        if(response==3)    
        {
            jButton1.setText("Sell Book");
            jScrollPane1.setVisible(false);
            jTextArea1.setVisible(false);
            jLabel3.setVisible(true);
            jTextField2.setVisible(true);
            jLabel2.setText("Title");
            jLabel3.setText("Quantity");
            jTextField1.setText("");
            
        }
    }
    void functieAdmin()
    {
        String[] options = new String[] {"User","Carte","Report","Cancel"};
        int response = JOptionPane.showOptionDialog(null, "What operation you want to do?", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
        if(response==0)    
        {
           
            functie1();
            
        }
        if(response==1)    
        {
            functie2();
        }
        if(response==2)    
        {
           jButton2.setText("Report");
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);  
            jScrollPane2.setVisible(false);
            jTextArea2.setVisible(false);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
             jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jComboBox1.insertItemAt("csv", 0);
            jComboBox1.insertItemAt("pdf", 1);
        }
         
    }
    public void functie1()
    {
        String[] options = new String[] {"Read","Update","Create","Delete","Cancel"};
        int response = JOptionPane.showOptionDialog(null, "What operation you want to do?", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
        if(response==0)    
        {
            jButton2.setText("ReadUsers");
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);  
            jScrollPane2.setVisible(true);
            jTextArea2.setVisible(true);
        }
        if(response==1)    
        {
            jButton2.setText("UpdateUser");
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel4.setText("Username");
            jLabel5.setText("Noua parola");
            jLabel6.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(false);
            jScrollPane2.setVisible(false);
            jTextArea2.setVisible(false);
            
        }
        if(response==2)    
        {
           jButton2.setText("CreateUser");
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel4.setText("Username");
            jLabel5.setText("Parola");
            jLabel6.setVisible(true);
            jLabel6.setText("Type");
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
             jScrollPane2.setVisible(false);
            jTextArea2.setVisible(false);
        }
        if(response==3)    
        {
           jButton2.setText("DeleteUser");
            jLabel4.setVisible(true);
            jLabel5.setVisible(false);
            jLabel4.setText("Username");
            jLabel6.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jScrollPane2.setVisible(false);
            jTextArea2.setVisible(false);
        }
         if(response==4) 
         {
             functieAdmin();
         }
    }
    public void functie2()
    {
        String[] options = new String[] {"Read","Update","Create","Delete","Cancel"};
        int response = JOptionPane.showOptionDialog(null, "What operation you want to do?", "Optiune",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[0]);
        if(response==0)    
        {
            jButton2.setText("ReadBook");
            jLabel4.setVisible(true);
            jLabel4.setText("Title");
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);  
            jScrollPane2.setVisible(true);
            jTextArea2.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
            
            
        }
        if(response==1)    
        {
            jButton2.setText("UpdateBook");
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel4.setText("Titlu");
            jLabel5.setText("Price");
            jLabel6.setText("Quantity");
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jScrollPane2.setVisible(false);
            jTextArea2.setVisible(false);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
            
        }
        if(response==2)    
        {
           jButton2.setText("CreateBook");
            jLabel4.setVisible(true);jLabel4.setText("Title");
            jLabel5.setVisible(true); jLabel5.setText("Author");
            jLabel6.setVisible(true);jLabel6.setText("Gen");
            jLabel7.setVisible(true);jLabel7.setText("Cantitate");
            jLabel8.setVisible(true);jLabel8.setText("Pret");
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
            jScrollPane2.setVisible(false);
            jTextArea2.setVisible(false);
        }
        if(response==3)    
        {
           jButton2.setText("DeleteBook");
            jLabel4.setVisible(true);
            jLabel5.setVisible(false);
            jLabel4.setText("Title");
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
            jScrollPane2.setVisible(false);
            jTextArea2.setVisible(false);
        }
         if(response==4) 
         {
             functieAdmin();
         }
    }
    public String getText()
    {
        return jTextField1.getText();
    }
    public String getInfo1()
    {
        return jTextField3.getText();
    }
    public String getInfo2()
    {
        return jTextField4.getText();
    }
    public String getInfo3()
    {
        return jTextField5.getText();
    }
    public String getInfo4()
    {
        return jTextField6.getText();
    }
    public String getInfo5()
    {
        return jTextField7.getText();
    }
    public String getUsername()
    {
        d=new ShareData();
        return d.getUsername();
    }
    public String getText2()
    {
        return jTextField2.getText();
    }
    public String getNameButton()
    {
        return jButton1.getText();
    }
    public String getNameButton1()
    {
        return jButton2.getText();
    }
    public void setList(List<String> s,String str) 
    {
        jLabel1.setVisible(true);
        jLabel1.setText(str);
        for(int i=0;i<s.size();i++){
            try {
                jTextArea1.insert(s.get(i)+"\n",jTextArea1.getLineStartOffset(i));
            } catch (BadLocationException ex) {
                Logger.getLogger(BookStoreOperation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    public void setMessage(String s)
    {
         JOptionPane.showMessageDialog(this,s);
    }
    public void addGenreListener(ActionListener listenForGenreButton)
    {
        jButton1.addActionListener(listenForGenreButton);
    }
    public void addListener(ActionListener listenForButton)
    {
        jButton2.addActionListener(listenForButton);
    }
    public void displayErrorMessage(String s)
    {
        JOptionPane.showMessageDialog(this,s);
        jTextField1.setText("");
    }
    public void setUser(List<String> s)
    {
        for(int i=0;i<s.size();i++){
            try {
                jTextArea2.insert(s.get(i),jTextArea2.getLineStartOffset(i));
            } catch (BadLocationException ex) {
                Logger.getLogger(BookStoreOperation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    public void setBook(List<String> s)
    {
        for(int i=0;i<s.size();i++){
                jTextArea2.append(s.get(i)+"\n");
        }
    }
    public void setValori(String s)
    {
            try {
                jTextArea2.insert(s,jTextArea2.getLineStartOffset(0));
            } catch (BadLocationException ex) {
                Logger.getLogger(BookStoreOperation.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    public String getTypeReport()
    {
        return (String)jComboBox1.getSelectedItem();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookStoreOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookStoreOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookStoreOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookStoreOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookStoreOperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
